---
output:
  html_document:
    theme:  united
    css: index.css
---


<div class="cd-fixed-bg cd-fixed-bg--1"> 
  <h1 class = "front-page-title" style = "padding-top:20%">
    P8105 Final Project - NY Organ Donation 
  <h1>
</div> 

<div class="cd-fixed-bg cd-fixed-bg--2"> 
  <h1 class = "front-page-title" style = "padding-top:5%">
    In need of donation
  <h1>
</div> 



```{r include=FALSE, warning = FALSE, message = FALSE }
library(tidyverse)
library(ggplot2)
donor_share_time_compare = read.csv("data/state_donor_share.csv") %>%
  janitor::clean_names() %>%
  rename(state = x)
plot_1 = 
ggplot(donor_share_time_compare, aes(x = year, y = donor_designation_share, color = state)) +
  geom_point() +
  geom_smooth()

```

<div class = "plot_description">
  <h1> Plot #1 Title </h1>
  <h2> Plot description <h2>
<div>




<section class="plotting_main">
  <div class = "plot_1_plot">
  ```{r, warning = FALSE, message = FALSE, echo=FALSE}
  # plot part 
  plot_1   
  ```
  </div>
  
  <div class = "plot_1_description">
  <span>lalalallalalala<span>
  </div>
</section>